
# texture_pig/nodes/utils.py
import numpy as np
from PySide6.QtCore import QFile, QResource
from PySide6.QtGui import QIcon, QPixmap
from pathlib import Path

def luma(rgb3: np.ndarray) -> np.ndarray:
    """
    Rec.709 luma from an RGB array of shape (H,W,3), returns (H,W) float32 in [0..1].
    """
    rgb3 = np.asarray(rgb3, dtype=np.float32)
    return (0.2126 * rgb3[..., 0] + 0.7152 * rgb3[..., 1] + 0.0722 * rgb3[..., 2]).astype(np.float32)


def channel_value_with_alpha(rgba: np.ndarray, channel: str) -> np.ndarray:
    """
    Returns a single-channel array (H,W) in [0..1] from an RGBA image (H,W,4),
    treating transparent pixels as black for non-alpha channels.

    - channel: 'a' | 'luma' | 'r' | 'g' | 'b'
    - rgba: float32 array (H,W,4) with values in [0..1]

    For 'a', returns alpha directly.
    For 'r','g','b','luma', multiplies the selected channel by A.
    """
    if rgba is None:
        return np.zeros((1, 1), dtype=np.float32)

    arr = np.asarray(rgba, dtype=np.float32)
    if arr.ndim != 3 or arr.shape[-1] != 4:
        return np.zeros((1, 1), dtype=np.float32)

    r = arr[..., 0]
    g = arr[..., 1]
    b = arr[..., 2]
    a = arr[..., 3]

    ch = (channel or 'a').lower()
    if ch == 'a':
        base = a
    elif ch == 'luma':
        base = luma(arr[..., :3])
        base = base * a
    elif ch == 'r':
        base = r * a
    elif ch == 'g':
        base = g * a
    elif ch == 'b':
        base = b * a
    else:
        # Unknown channel → default to alpha
        base = a

    return np.clip(base, 0.0, 1.0).astype(np.float32)


def extract_mask(rgba: np.ndarray, channel: str = 'a') -> np.ndarray:
    """
    Returns a mask shaped (H,W,1) in [0..1] from an RGBA image,
    applying the “transparent pixels = black” rule for non-alpha channels.

    This is just channel_value_with_alpha(...)[..., None].
    """
    m = channel_value_with_alpha(rgba, channel)
    if m.ndim == 2:
        return m[..., None]
    # Fallback to ensure shape (H,W,1)
    return np.reshape(m, m.shape + (1,))

def resolve_qt_resource_or_fs(resource_path: str) -> QIcon:
    """
    Return a QIcon. If :/ resource exists, use it. Otherwise map :/ui/... to
    the package filesystem path: <site-packages or repo>/texture_pig/ui/...
    """
    # First try as a Qt resource
    icon = QIcon(resource_path)
    if not icon.isNull():
        return icon

    # Fallback: try filesystem if Qt resource fails
    if resource_path.startswith(":/"):
        # Map :/ui/... to texture_pig/ui/...
        try:
            import texture_pig
            pkg_dir = Path(texture_pig.__file__).resolve().parent
            rel = resource_path.lstrip(":/")           # "ui/icons/gradient_linear_128.png"
            fs_path = pkg_dir / rel                    # <pkg>/ui/icons/...
            if fs_path.exists():
                fs_icon = QIcon(str(fs_path))
                if not fs_icon.isNull():
                    return fs_icon
                else:
                    print(f"[Icon] Failed to load: {fs_path}")
            else:
                print(f"[Icon] Not found: {resource_path} (tried {fs_path})")
        except Exception as e:
            print(f"[Icon] Error loading {resource_path}: {e}")
    else:
        # Already a filesystem path
        fs_icon = QIcon(resource_path)
        if fs_icon.isNull():
            print(f"[Icon] Filesystem icon isNull: {resource_path}")
        return fs_icon

    # Final empty icon (UI still renders a button)
    return QIcon()

def register_qt_resources():
    """
    Try to load compiled Qt resources first:
      - Python module (icons_rc.py) generated by pyside6-rcc under texture_pig.ui
      - Binary .rcc file next to texture_pig/ui/resources.rcc
    Falls back silently to filesystem if neither is available.
    """
    # 1) Compiled Python resource module
    try:
        from texture_pig.ui import icons_rc
        return True
    except Exception:
        pass

    # 2) Compiled binary .rcc (optional)
    try:
        import texture_pig
        pkg_dir = Path(texture_pig.__file__).resolve().parent
        rcc_path = pkg_dir / "ui" / "resources.rcc"
        if rcc_path.exists():
            if QResource.registerResource(str(rcc_path)):
                return True
    except Exception:
        pass

    # Fallback to filesystem via resolve_qt_resource_or_fs()
    return False

def load_stylesheet_with_fallback(app):
    """
    Try to load :/ui/qss/style.qss, else texture_pig/ui/qss/style.qss on disk.
    """
    qss_resource = ":/ui/qss/style.qss"

    # Try resource first
    f = QFile(qss_resource)
    if f.open(QFile.ReadOnly | QFile.Text):
        data = f.readAll()
        try:
            css = bytes(data).decode("utf-8")
        except Exception:
            css = str(data)
        app.setStyleSheet(css)
        return

    # Fallback to package filesystem
    try:
        import texture_pig
        pkg_dir = Path(texture_pig.__file__).resolve().parent
        fs_qss = pkg_dir / "ui" / "qss" / "style.qss"
        if fs_qss.exists():
            css = fs_qss.read_text(encoding="utf-8")
            app.setStyleSheet(css)
            return
        else:
            print("[QSS] Stylesheet not found:", fs_qss)
    except Exception as e:
        print("[QSS] Error loading stylesheet:", e)
